---

- hosts: all
  roles:
    - { role: common, tags: common }
    - { role: slurm_common, tags: slurm_common }

- hosts: d
  roles:
    - { role: slurm_database, tags: slurm_database }

- hosts: n
  roles:
    - { role: nfs_server, tags: nfs_server }

- hosts: s
  roles:
    - { role: nfs_client, tags: nfs_client }
    - { role: slurm_server, tags: slurm_server }

- hosts: c
  roles:
    - { role: nfs_client, tags: nfs_client }
    - { role: slurm_compute, tags: slurm_compute }

- hosts: l
  roles:
    - { role: nfs_client, tags: nfs_client }
    - { role: slurm_login, tags: slurm_login }
