---

- name: Slurm Compute RPM List
  ansible.builtin.set_fact:
    pkg_list:
      - slurm-slurmd
      - slurm-pam_slurm
      - slurm-contribs

- name: Slurm Compute RPM Install
  ansible.builtin.dnf:
    name: "{{ pkg_list }}"
    state: installed
  environment: "{{ proxy_env }}"

- name: Configure Slurmd
  ansible.builtin.shell:
    cmd: echo "SLURMD_OPTIONS=-Z --conf-server {{ hostvars['server']['ansible_facts']['nodename'] }} --conf \"State=CLOUD\"" > /etc/sysconfig/slurmd
  args:
    creates: "/etc/sysconfig/slurmd"

- name: Slurm Service
  ansible.builtin.service:
    name: slurmd
    state: started
    enabled: yes
